### ISSUE TITLE
As a user I would like to manually choose item purchase frequency by selecting buttons.

### ISSUE THREAD

**Issue by zeeatwork** [the-collab-lab/tcl-23-smart-shopping-list#32]
This is a sub-issue for #14 

UI Mock-Up
<img width="742" alt="Screen Shot 2021-05-22 at 10 03 30 PM" src="https://user-images.githubusercontent.com/23660204/119245758-8e56ec00-bb49-11eb-9caa-2799ea6ad455.png">

<img width="230" alt="Screen Shot 2021-05-22 at 10 03 02 PM" src="https://user-images.githubusercontent.com/23660204/119245747-7bdcb280-bb49-11eb-8a22-c1a86067877b.png">

Convert the current dropdown option in AddItem.js to buttons.
Use uniform styling from Figma, if the buttons have been created

**Comment by jamesncox** [comment]
Just want to make sure we are all on the same page about the overall design for `/add-item`

It looks like @apdsrocha updated the buttons to checkboxes. Does this sound good to everyone still?

![add-new-item-checkboxes](https://user-images.githubusercontent.com/47455758/119276454-f0623080-bbdf-11eb-84f7-30edec819313.jpg)
