### ISSUE TITLE
Add icons to List, Home, and addItem using Figma wireframes as a guide.

### ISSUE THREAD

**Issue by zeeatwork** [the-collab-lab/tcl-23-smart-shopping-list#34]
This is a sub-issue related to #14 

UI Mock Ups:

<img width="114" alt="Screen Shot 2021-05-22 at 10 17 50 PM" src="https://user-images.githubusercontent.com/23660204/119245971-8dbf5500-bb4b-11eb-83e4-c223b0db28f7.png">

<img width="112" alt="Screen Shot 2021-05-22 at 10 18 17 PM" src="https://user-images.githubusercontent.com/23660204/119245985-9ca60780-bb4b-11eb-8aef-785ff87a19e2.png">

<img width="113" alt="Screen Shot 2021-05-22 at 10 18 31 PM" src="https://user-images.githubusercontent.com/23660204/119245988-a596d900-bb4b-11eb-8576-506cf0864e63.png">

Icons for landing page
https://shape.so/

**Comment by jamesncox** [comment]
ICONS (listed by Heroicon searchable name)

1. chevron-right
2. trash
3. pencil-alt <-- INCORPORATED IN #39 
4. clipboard-check <-- INCORPORATED in #39 
5. x
6. clock <-- 1/2 INCORPORATED in #32 for `AddItem.js`
