### ISSUE TITLE
As a user, I would like option to have my token to remain visible while adding to an existing list or toggle to hide it.

### ISSUE THREAD

**Issue by zeeatwork** [the-collab-lab/tcl-23-smart-shopping-list#42]
[ ] - drop-down is recommended because a user could have multiple lists (could discuss a toggle if we implement a sign out button)

<img width="112" alt="Screen Shot 2021-05-22 at 11 32 29 PM" src="https://user-images.githubusercontent.com/23660204/119247264-01fef600-bb56-11eb-86d2-807b947ae3a9.png">

**Comment by jamesncox** [comment]
We already use SweetAlert, so maybe just incorporate a SweetAlert with their token in a button with `showToken()` onClick? then they can copy and paste from there?
