### ISSUE TITLE
Update `List.js` input and verbiage to reflect Figma.

### ISSUE THREAD

**Issue by jamesncox** [the-collab-lab/tcl-23-smart-shopping-list#51]
Update the Header and input design to resemble our [Figma](https://www.figma.com/file/Gd4a2z8c5iNG6b3ZWs36g4/Smart-Shopping-List?node-id=0%3A1) design.

`List.js` header and input
![list-h1-input-figma](https://user-images.githubusercontent.com/47455758/119728664-5990b080-be39-11eb-976d-5d6b865cd53a.jpg)

**Comment by apdsrocha** [comment]
I'll try my hand at this one and call for help if I'm too stuck 😆

**Comment by jamesncox** [comment]
I think this needs to be re-merged somehow back into main if that's possible.
