### ISSUE TITLE
BUG:  Fix unwanted NavBar Behaviour

### ISSUE THREAD

**Issue by jamesncox** [the-collab-lab/tcl-23-smart-shopping-list#59]
tailwind utility classes `absolute bottom-0` is forcing the navigation to that spot no matter what. Which means list items get stuck behind it and then flow past it.

# Media
![Screenshot (193)](https://user-images.githubusercontent.com/47455758/120082252-7b7f7280-c087-11eb-8ad0-e6654da21709.png)

# To Do
Refactor both `App.js` top-level utility classes and `NavBar.js` utility classes so that the NavBar remains at the bottom but "pushes down" as the list items grow.

**Comment by jssckbl** [comment]
Hiya! What's the branch to test this PR out on?
