### ISSUE TITLE
8. As a user, I want to mark an item on my shopping list as purchased so the app can learn how often I buy different items.

### ISSUE THREAD

**Issue by stacietaylorcima** [the-collab-lab/tcl-23-smart-shopping-list#9]
AC:

* User is able to tap a checkbox or similar UI element to mark an item in the list as purchased
* Item should be shown as checked for 24 hours after the purchase is made (i.e. we assume the user does not need to buy the item again for at least 1 day)

**Comment by yenly** [comment]
https://raw.githubusercontent.com/the-collab-lab/smart-shopping-list/main/_resources/wireframes/list-populated.png

**Comment by jamesncox** [comment]
`Item should be shown as checked for 24 hours after the purchase is made (i.e. we assume the user does not need to buy the item again for at least 1 day)`

I need clarity for this particular AC. Does this mean that the checkbox is disabled/un-checkable for 24 hours? Or does this mean that, left alone, any item will remain visibly checked, and after 24 hours has passed, it will become unchecked?

**Comment by skylerwshaw** [comment]
> `Item should be shown as checked for 24 hours after the purchase is made (i.e. we assume the user does not need to buy the item again for at least 1 day)`
> 
> I need clarity for this particular AC. Does this mean that the checkbox is disabled/un-checkable for 24 hours? Or does this mean that, left alone, any item will remain visibly checked, and after 24 hours has passed, it will become unchecked?

The latter, we should show it checked if we're within 24 hours of the latest time it was checked. This does beg the question about the interaction of the user unchecking. What do you think is sensible behavior?

**Comment by jamesncox** [comment]
> This does beg the question about the interaction of the user unchecking. What do you think is sensible behavior?

We decided to allow the user to uncheck a checkbox that is still less than 24 hours old. What if they accidentally marked it as purchased? Or what if they realize they need MORE milk for breakfast tomorrow? 

So when the item is marked as purchased, the checkbox remains checked for 24 hours, BUT if the user unchecks it, we update Firestore with `last_purchased: null` again.
